### ISSUE TITLE
ES6 import support

### ISSUE THREAD

**Issue by olimsaidov** [jballant/CommonJSAutoComplete#6]
Any plans to implement es6 style imports?

**Comment by jballant** [comment]
Looking into it. The syntax is very different.

It might be relatively straightforward to do this syntax:

``` javascript
//--myFunc.js--
export default function() {
   return 'foo';
};

// --main.js--
import * as myFunc from "../path/to/myFunc.js";
console.log(myFunc()); // logs 'foo'
```

But the import statement syntax below doesn't give me any information to work with when determining the file to use for the import statement until you have already typed out the module:

``` javascript
//--myModule.js--
export function getFoo() {
   return 'foo';
};

// --main.js--
import { getFoo } from "../path/to/myModule.js";
console.log(getFoo()); // logs 'foo'
```

Not sure if Jetbrains provides a way currently with their javascript library to quickly look through the exports of all the files in a project. If it does, then it might be possible to add support for it. So that's what I am investigating at the moment.

**Comment by eXaminator** [comment]
+1

**Comment by jballant** [comment]
I have a branch up with basic support simple imports: https://github.com/jballant/CommonJSAutoComplete/tree/feature-es6-import.

You can download and manually install the zip file if you would like to try it out.

At this point, the autocomplete will work for importing a complete module like this:

``` javascript
// ./lib/MyClass.js
export default class MyClass {
    // class
}

// ./main.js
import MyClass from './ilb/MyClass'; 
// " from './lib/MyClass' will autocomplete once you've typed "import MyClass"
```

It only works with the default export at this point. I'm investigating other syntaxes.

**Comment by jballant** [comment]
Basic ES6 import support is in the current version, so I will close this issue for now.
